@startuml
class hero{
    - name
    - health
    - experiencePoints
    - powerPoints
    - armorPoints
    - level
}

class specialty {
    - name
    - healthAtLevel1
    - powerAtLevel1
    - armorAtLevel1
    - AdditionalPowerAgainstWeakerSpec
    - weakerSpec
}
class cardPack{
    - name
    - tokenCost
    - size
    - probability
}
class gatchaRate {
      - probability
}
class rarity{
      - name
}
class deck  {
    - name
}
class player {

}
player "1"- "1" deck:\t\t\t\t\t
hero "*"-"1" rarity:\t\t\t\t
hero "*" --o "1" specialty
deck "*" --"*" hero :"\t\t\t\t\t"
cardPack "*" --"*" hero :"\t\t\t\t"
(cardPack,rarity) .. gatchaRate
@end
refactor specialty