@startuml
class Hero{
    - name
    - health
    - experiencePoints
    - powerPoints
    - armorPoints
    - level
}

class Specialty {
    - name
    - healthAtLevel1
    - powerAtLevel1
    - armorAtLevel1
    - additionalPowerAgainstWeakerSpec
    - weakerSpeciality
}
class CardPack{
    - name
    - tokenCost
    - size
}
class ProbabilityByRarity {
      - probability

}
class Rarity{
      - name
}
class Deck  {
    - name
}
class Player {

}
class BattleHistory{
     - opponent
     - result
     - battleDate
}
Player "1"- "1" Deck:\t\t\t\t\t
Player "*"-"*" BattleHistory:\t\t\t\t
Hero "*"-"1" Rarity:\t\t\t\t
Hero "*" --o "1" Specialty
Deck "*" --"*" Hero :"\t\t\t\t\t"
CardPack "*" --"*" Hero :"\t\t\t\t"
(CardPack,Rarity) .. ProbabilityByRarity
@end